name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-release-binaries:
    name: Build release binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash tools/build-release-binaries.sh artifacts
      - uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: artifacts/
          retention-days: 7

  test-linux:
    name: Test Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazel test //integration-tests:integration_test

  test-macos:
    name: Test macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazel test //integration-tests:integration_test

  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazel test //integration-tests:integration_test
